update
front-end-by-rimantas/14-grupe-portfolio-daniels pull request #41
Opened 2020-04-22 17:06 UTC by Jul1us5

2020-04-22 17:08 UTC, QurTu approved these changes

2020-04-22 19:41 UTC, belauzas requested changes

2020-04-22 19:41 UTC, belauzas commented on js/main.js
> +// window.onresize = function(){ location.reload(); }
KAS ČIA?????? 😱 😱 😱 😱 😱 😱 😱 
visi pokyčiai privalo būti sklandūs:
- jei tai stilius, tik CSS @media dėka
- jei tai JS dalykai, kiekvienas komponentas gali stebėti ekrano dydžio pasikeitimą ir save pagal poreikį persipiešti.
Tad, išmetam, o susijusios problemos, kurias buvo bandoma taip išspręsti - taisyti.

2020-04-22 19:41 UTC, belauzas commented on css/hero.css
> +        margin-top: calc(50vh - 110px) !important;
Išmetam !important, to jei norimas stilius nesuveikia:
- perdėlioti CSS failų eiliškumą, jog komponentai būtų žemiau bendrinio stiliaus;
- arba padaryti didesnio specifiškumo selector'ių.

2020-04-22 19:41 UTC, belauzas commented on css/hero.css
> +    margin-top: calc(50vh - 110px) !important;
Išmetam !important, to jei norimas stilius nesuveikia:
- perdėlioti CSS failų eiliškumą, jog komponentai būtų žemiau bendrinio stiliaus;
- arba padaryti didesnio specifiškumo selector'ių.

2020-04-22 19:41 UTC, belauzas commented on css/nav.css
>      margin-top: 16px !important;
Išmetam !important, to jei norimas stilius nesuveikia:
- perdėlioti CSS failų eiliškumą, jog komponentai būtų žemiau bendrinio stiliaus;
- arba padaryti didesnio specifiškumo selector'ių.

2020-04-23 07:07 UTC, Eiman99 approved these changes

2020-04-23 07:07 UTC, Eiman99 approved these changes

2020-04-23 07:08 UTC, Eiman99 approved these changes

2020-04-23 07:08 UTC, Eiman99 approved these changes

2020-04-23 07:09 UTC, Eiman99 approved these changes

2020-04-23 07:10 UTC, Eiman99 approved these changes

2020-04-23 13:49 UTC, closed without merging